name: Docker Image CI

on:
  push:
    branches: [ "master", "main", "mainline" ]
  pull_request:
    branches: [ "master", "main", "mainline" ]
  schedule:
    - cron:  '05 15 * * 0'
  workflow_dispatch:
    inputs:
      TAG_COMMAND:
        description: 'An optional custom command whos output will be used to tag the built image.'
        required: false

jobs:
  call-upstream-workflow:
    uses: snw35/cicd/.github/workflows/github.yaml@main
    secrets: inherit
